host:
	make -f host.mk host

csim:
	make -f firmware.mk csim

csynth: 
	make -f firmware.mk csynth

link:
	make -f firmware.mk link
	
package:
	make -f firmware.mk package

run: 
	make -f firmware.mk run
